version: "3.8"
services:
  dklodd:
    image: minpeter/dklodd:latest
    container_name: dklodd
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.dklodd.entrypoints=web
      - traefik.http.routers.dklodd.rule=Host(`dklodd.traefik.me`)
    networks:
      - traefik

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.me`)
      - traefik.http.routers.traefik.service=api@internal
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --entrypoints.web.address=:80
    ports:
      - 8080:80
    networks: [traefik]

networks:
  traefik:
    external: true
